using Microsoft.AspNetCore.Authentication; using Microsoft.AspNetCore.Authentication.Cookies; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using SolicitudIT_Isertec.Services;
namespace SolicitudIT_Isertec.Controllers;
public class AccountController:Controller { private readonly AuthService auth; public AccountController(AuthService auth)=>this.auth=auth;
 [AllowAnonymous] public IActionResult Login(string? returnUrl=null)=>View(new LoginVm{ReturnUrl=returnUrl});
 [HttpPost,AllowAnonymous,ValidateAntiForgeryToken] public async Task<IActionResult> Login(LoginVm m){ if(!ModelState.IsValid)return View(m); var u=await auth.ValidateAsync(m.Login,m.Password); if(u is null){ModelState.AddModelError("","Usuario/correo o contraseña incorrectos.");return View(m);} await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,AuthService.Principal(u),new AuthenticationProperties{IsPersistent=m.Remember}); return LocalRedirect(m.ReturnUrl??Url.Action("Index","Home")!); }
 [Authorize] public async Task<IActionResult> Logout(){await HttpContext.SignOutAsync();return RedirectToAction("Login");} [AllowAnonymous] public IActionResult AccessDenied()=>View();
 [AllowAnonymous] public async Task<IActionResult> Setup(){ if(await auth.HasUsersAsync()) return RedirectToAction("Login"); return View(); }
 [HttpPost,AllowAnonymous,ValidateAntiForgeryToken] public async Task<IActionResult> Setup(string nombre,string apellido,string usuario,string email,string password){ if(await auth.HasUsersAsync()) return RedirectToAction("Login"); if(string.IsNullOrWhiteSpace(nombre)||string.IsNullOrWhiteSpace(usuario)||string.IsNullOrWhiteSpace(email)||password.Length<8){ModelState.AddModelError("","Completa los datos y usa una contraseña de al menos 8 caracteres.");return View();} await auth.CreateAdminAsync(nombre,apellido,usuario,email,password); return RedirectToAction("Login"); }
}
public class LoginVm { [System.ComponentModel.DataAnnotations.Required] public string Login{get;set;}=""; [System.ComponentModel.DataAnnotations.Required] public string Password{get;set;}=""; public bool Remember{get;set;} public string? ReturnUrl{get;set;} }
